service: medcloud-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
      Resource:
        - "arn:aws:dynamodb:sa-east-1:928705830820:table/medcloudbr"
  apiName: medcloudbr
  apiGateway:
    restApiId: 7ql9ymkg4m
    restApiRootResourceId: o4i2ywt3xh
    restApiResources:
      '/patients': kbsmpw
      '/patients/{id}': bffabg
      '/login': zyw90i

package:
  include:
    - node_modules/**

functions:
  getPatients:
    handler: functions/patient/getPatients.handler
  getPatient:
    handler: functions/patient/getPatient.handler
  createPatient:
    handler: functions/patient/createPatient.handler
  updatePatient:
    handler: functions/patient/updatePatient.handler
  deletePatient:
    handler: functions/patient/deletePatient.handler
  login:
    handler: functions/login/login.execute
  authorizer:
    handler: helpers/authorizer.authorizer
  addBatch:
    handler: helpers/batchAddUsers.handler
  